offers/urls.py
from django.urls import path

from .views import (index, CreateOffer, 
    DetailOffer, respond_to_offer, MyOffers, 
    set_selected_responder, reset_selected_responder, list_user_requests, search
)

app_name = 'offers'
urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('offers/new/', CreateOffer.as_view(extra_context={'title': 'Новая заявка'}), name='add_offer'),
    path('offers/<int:pk>/', DetailOffer.as_view(), name='detail_offer'),
    path('offers/<int:pk>/respond/', respond_to_offer, name='respond_offer'),
    path('myoffers/', MyOffers.as_view(extra_context={'title': 'Мои заявки'}), name='myoffers'),
    path('myoffers/select/', set_selected_responder, name='select_responder'),
    path('myoffers/reset/', reset_selected_responder, name='reset_responder'),
    path('myrequests/', list_user_requests, name='list_requests'),
]

rar_net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('offers.urls')),
    path('users/', include('users.urls')),
    path('locations/', include('locations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path

from .views import logout_user, login_user, RegisterUser

app_name = 'users'
urlpatterns = [
    path('logout/', logout_user, name='logout'),
    path('login/', login_user, name='login'),
    path('register/', RegisterUser.as_view(extra_context={'title': 'Регистрация'}), name='register'),
]

offers/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Offer(models.Model):
    categories = [
        ('buy', 'купить',),
        ('sell', 'продать',)
    ]

    statuses = [
        ('active', 'активно',),
        ('closed', 'закрыто',)
    ]

    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'
        ordering = ['id', 'title']

    title = models.CharField('название', max_length=150)
    description = models.CharField('описание', max_length=400, blank=True)
    category = models.CharField('категория', max_length=20, choices=categories, default='buy')
    status = models.CharField('статус', max_length=20, choices=statuses, default='active')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='author', verbose_name='владелец')
    responders = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='откликнулись', related_name='responders', blank=True)
    selected_responder = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='выбран', related_name='selected_responder', blank=True, null=True)
    pub_date = models.DateTimeField('дата публикации', auto_now_add=True)

    def __str__(self):
        return f'{self.title} | {self.author}'

class Photo(models.Model):
    class Meta:
        verbose_name = 'фото'
        verbose_name_plural = 'фотографии'

    offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    img = models.ImageField('фото', upload_to='offers/%Y/%m/')

    def __str__(self):
        return f'{self.img}'

offers/forms.py
from django import forms

from .models import Offer

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleImageField(forms.ImageField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class OfferForm(forms.ModelForm):
    imgs = MultipleImageField(label='Изображения')

    class Meta:
        model = Offer
        fields = ['title', 'description', 'category', 'imgs']

offers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotAllowed, HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q

from .forms import OfferForm
from .models import Photo, Offer

# Create your views here.

def index(request):
    return render(request, 'offers/index.html', context={'offers': Offer.objects.filter(status='active')})

class CreateOffer(LoginRequiredMixin, generic.CreateView):
    template_name = 'offers/add_offer.html'
    redirect_field_name = ''
    form_class = OfferForm

    def get_success_url(self):
        return reverse_lazy('offers:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        self.object = form.save()

        images = form.cleaned_data['imgs']
        for img in images:
            Photo.objects.create(img=img, offer=self.object)

        return HttpResponseRedirect(self.get_success_url())

class DetailOffer(generic.DetailView):
    model = Offer
    template_name = 'offers/detail_offer.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DetailOffer, self).get_context_data(*args, **kwargs)
        context['title'] = context['offer'].title
        return context

@login_required(redirect_field_name='')
def respond_to_offer(request, pk):
    if request.method == 'GET':
        offer = get_object_or_404(Offer, pk=pk)
        offer.responders.add(request.user)
        offer.save()

        return redirect('offers:index')
    else:
        return HttpResponseNotAllowed(['POST'])

class MyOffers(LoginRequiredMixin, generic.ListView):
    model = Offer
    template_name = 'offers/my_offers.html'
    redirect_field_name = ''

    def get_queryset(self):
        return self.request.user.author.all()

@login_required(redirect_field_name='')
def set_selected_responder(request):
    if request.method == 'POST':
        if request.POST is not None:
            offer_pk = request.POST['offer_pk']
            responder_pk = request.POST['responder_pk']

            offer = get_object_or_404(Offer, pk=offer_pk)
            responder = get_object_or_404(get_user_model(), pk=responder_pk)

            if offer.author == request.user:
                offer.selected_responder = responder
                offer.status = 'closed'
                offer.save()
            else:
                return HttpResponseForbidden()

            return redirect('offers:myoffers')
    else:
        return HttpResponseNotAllowed(['POST'])

@login_required(redirect_field_name='')
def reset_selected_responder(request):
    if request.method == 'POST':
        if request.POST is not None:
            offer_pk = request.POST['offer_pk']

            offer = get_object_or_404(Offer, pk=offer_pk)

            if offer.author == request.user:
                offer.selected_responder = None
                offer.status = 'active'
                offer.save()
            else:
                return HttpResponseForbidden()

            return redirect('offers:myoffers')
    else:
        return HttpResponseNotAllowed(['POST'])

@login_required(redirect_field_name='')
def list_user_requests(request):
    user_requests = request.user.responders.all()
    return render(request, 'offers/my_requests.html', context={'requests': user_requests})

def search(request):
    if request.GET is not None:
        query = request.GET['q']
        sort_type = request.GET['sort_type']

        initial_queryset = Offer.objects.filter(status='active')
        sorting_types = {
            'everywhere': lambda: initial_queryset,
            'same_country': lambda: initial_queryset.filter(author__country=request.user.country),
            'same_city': lambda: initial_queryset.filter(author__city=request.user.city),
        }

        sorted_offers = sorting_types.get(sort_type)()

        if query is not None:
            sorted_offers = sorted_offers.filter(Q(title__icontains=query) | Q(description__icontains=query))

        return render(request, 'offers/search_page.html', context={'offers': sorted_offers, 'q': query, 'sort_type': sort_type})

offers/templates/offers/add_offer.html
{% extends "offers/base_site.html" %}
{% load static %}

{% block page_specific_styles %}
<link rel="stylesheet" href="{% static "offers/css/pages/createOffer.css" %}">
{% endblock page_specific_styles %}

{% block content %}
<section class="fancy-borders" id="create-offer">
    <form method="post" enctype="multipart/form-data">
        <div id="inputs" class="flex">
            {% csrf_token %}
            {{form.as_div}}
        </div>
        <input class="fancy-borders focus-button" type="submit" value="Разместить">
    </form>
</section>
{% endblock content %}

offers/templates/offers/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "offers/css/global.css" %}">
    <link rel="stylesheet" href="{% static "offers/css/normalize.css" %}">
    <title>{{title|default:'Rar-Net'}}</title>

    {% block page_specific_styles %}{% endblock page_specific_styles %}
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
    {% block body %}{% endblock body %}
</body>
</html>

offers/templates/offers/base_site.html
{% extends "offers/base.html" %}
{% load static %}

{% block body %}

{% block header %}
<header>
    <nav class="flex">
        <ul class="nav-links">
            <li><a href="{% url "offers:index" %}">Главная</a></li>
            <li><a href="{% url "offers:list_requests" %}">Мои отклики</a></li>
            <li><a href="{% url "offers:myoffers" %}">Мои заявки</a></li>
            <li><a href="{% url "offers:add_offer" %}">Добавить заявку</a></li>
        </ul>
    </nav>
    <img id="logo" src="{% static "offers/img/logo.png" %}" alt="rar-net">
</header>
{% endblock header %}

<main>
    {% block content %}{% endblock content %}
</main>

{% block footer %}
<footer>
    <ul class="nav-links">
        <li><a href="https://loooltooot.github.io" target="_blank">Emir Zakrewski</a></li>
        <li><a href="https://t.me/loooltooot" target="_blank">Телеграм</a></li>
    </ul>
</footer>
{% endblock footer %}

<script src="{% static "offers/js/jquery.min.js" %}"></script>
{% block page_specific_scripts %}{% endblock page_specific_scripts %}

{% endblock body %}

offers/templates/offers/detail_offer.html
{% extends "offers/base_site.html" %}
{% load static ru_plural %}

{% block page_specific_styles %}
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
/>
<link rel="stylesheet" href="{% static "offers/css/pages/detailOffer.css" %}">
{% endblock page_specific_styles %}

{% block content %}
{% include "offers/components/search.html" %}
<section id="detail-offer" class="flex fancy-borders">
    <div class="content">
        <h2>{{offer.title}}</h2>
        <div class="author-container">
            <span class="author">{{offer.author.username}}</span>
            {% if offer.author.country is not None %}
            <img class="flag" title="{{offer.author.country.name}}" src="{% static "locations/flags/"|add:offer.author.country.flag %}" alt="">
            <span class="city">{{offer.author.city.name}}</span>
            {% endif %}
        </div>
        <span class="category {{offer.category|yesno:'buy,sell'}}">{{offer.get_category_display}}</span>
        <p>{{offer.description}}</p>
        <div class="action flex">
            {% if user.is_authenticated and user.username != offer.author.username and user not in offer.responders.all %}
                <a class="fancy-borders focus-button" href="{% url "offers:respond_offer" offer.id %}">Откликнуться</a>
            {% endif %}
            {% if offer.responders.count > 0 %}
                <span class="asked">Уже откликнулось: {{offer.responders.count|ru_plural:'человек,человека'}}</span>
            {% else %}
                <span class="asked">Станьте первым, кто откликнется</span>
            {% endif %}
        </div>
    </div>
    <div class="images swiper">
        <div class="swiper-wrapper">
            {% for image in offer.photo_set.all %}
                <div class="swiper-slide">
                    <img src="{{image.img.url}}">
                </div>
            {% endfor %}
        </div>
        <div class="swiper-pagination"></div>

        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
    </div>
</section>
{% endblock content %}

{% block page_specific_scripts %}
<script src="{% static "offers/js/searchBar.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script>
    const swiper = new Swiper('.swiper', {
        direction: 'horizontal',
        loop: true,

        // If we need pagination
        pagination: {
            el: '.swiper-pagination',
        },

        // Navigation arrows
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    })
</script>
{% endblock page_specific_scripts %}

offers/templates/offers/index.html
{% extends "offers/base_site.html" %}
{% load static offers_list %}

{% block content %}
{% include "offers/components/search.html" %}
{% offers_list %}
{% endblock content %}

{% block page_specific_scripts %}
<script src="{% static "offers/js/searchBar.js" %}"></script>
{% endblock page_specific_scripts %}

offers/templates/offers/my_offers.html
{% extends "offers/base_site.html" %}
{% load static %}

{% block page_specific_styles %}
<link rel="stylesheet" href="{% static "offers/css/pages/myoffers.css" %}">
{% endblock page_specific_styles %}

{% block content %}
{% include "offers/components/search.html" %}
<section id="myoffers">
    <ul class="myoffers-list">
        {% for offer in offer_list %}
        <li>
            <div class="fancy-borders">
                <div class="offer-info flex">
                    <a class="title" href="{% url "offers:detail_offer" offer.id %}">
                        <h3>{{offer.title}}</h3>
                    </a>
                    <span>{{offer.get_category_display}}</span>
                </div>
                <div>
                    {% if offer.selected_responder is None %}
                    <h4>Откликнулись:</h4>
                    <ul class="responders-list">
                        {% for responder in offer.responders.all %}
                        <li class="flex">
                            <div class="responder-info flex">
                                <span>{{responder.username}}</span>
                                {% if responder.country is not None %}
                                    <img class="flag" title="{{responder.country.name}}" src="{% static "locations/flags/"|add:responder.country.flag %}" alt="">
                                    <span>{{responder.city}}</span>
                                {% endif %}
                            </div>
                            <form action="{% url "offers:select_responder" %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="responder_pk" value="{{responder.id}}">
                                <input type="hidden" name="offer_pk" value="{{offer.id}}">
                                <input type="submit" value="выбрать" class="fancy-borders focus-button">
                            </form>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <h4>Выбран:</h4>
                    <div class="responder-info fancy-borders selected-responder">
                        <span>{{offer.selected_responder.username}}</span>
                        <span>{{offer.selected_responder.last_name}} {{offer.selected_responder.first_name}}</span>
                        <span>{{offer.selected_responder.email}}</span>
                        {% if offer.selected_responder.country is not None %}
                            <img class="flag" title="{{offer.selected_responder.country.name}}" src="{% static "locations/flags/"|add:offer.selected_responder.country.flag %}" alt="">
                            <span>{{offer.selected_responder.city}}</span>
                        {% endif %}
                        <form action="{% url "offers:reset_responder" %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="offer_pk" value="{{offer.id}}">
                            <input type="submit" value="отменить" class="fancy-borders focus-button">
                        </form>
                    </div>
                    {% endif %}
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</section>
{% endblock content %}

{% block page_specific_scripts %}
<script src="{% static "offers/js/searchBar.js" %}"></script>
{% endblock page_specific_scripts %}

offers/templates/offers/my_requests.html
{% extends "offers/base_site.html" %}
{% load static %}

{% block page_specific_styles %}
<link rel="stylesheet" href="{% static "offers/css/pages/myoffers.css" %}">
{% endblock page_specific_styles %}

{% block content %}
{% include "offers/components/search.html" %}
<section id="myrequests">
    <ul class="myoffers-list">
        {% for offer in requests %}
        <li>
            <div class="fancy-borders">
                <div class="offer-info flex">
                    <a class="title" href="{% url "offers:detail_offer" offer.id %}">
                        <h3>{{offer.title}}</h3>
                    </a>
                    <span>{{offer.get_category_display}}</span>
                    <div class="responder-info flex">
                        <span>{{offer.author.username}}</span>
                        {% if offer.author.country is not None %}
                            <img class="flag" title="{{offer.author.country.name}}" src="{% static "locations/flags/"|add:offer.author.country.flag %}" alt="">
                            <span>{{offer.author.city}}</span>
                        {% endif %}
                    </div>
                </div>
                {% if offer.selected_responder == user %}
                    <div class="responder-info fancy-borders selected-responder">
                        вас выбрали
                    </div>
                    <div class="author-info">
                        <h4>Данные для связи:</h4>
                        <span>{{offer.author.last_name}} {{offer.author.first_name}}</span>
                        <span>{{offer.author.email}}</span>
                    </div>
                {% else %}
                    <div class="responder-info fancy-borders not-selected-responder">
                        вас еще не выбрали
                    </div>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</section>
{% endblock content %}

{% block page_specific_scripts %}
<script src="{% static "offers/js/searchBar.js" %}"></script>
{% endblock page_specific_scripts %}

offers/templates/offers/search_page.html
{% extends "offers/index.html" %}
{% load offers_list %}

{% block content %}
{% include "offers/components/search.html" %}
<h2>Результаты поиска:</h2>
{% offers_list %}
{% endblock content %}