offers/urls.py
from django.urls import path

from .views import (index, CreateOffer, 
    DetailOffer, respond_to_offer, MyOffers, 
    set_selected_responder, reset_selected_responder, list_user_requests, search
)

app_name = 'offers'
urlpatterns = [
    path('', index, name='index'),
    path('search/', search, name='search'),
    path('offers/new/', CreateOffer.as_view(extra_context={'title': 'Новая заявка'}), name='add_offer'),
    path('offers/<int:pk>/', DetailOffer.as_view(), name='detail_offer'),
    path('offers/<int:pk>/respond/', respond_to_offer, name='respond_offer'),
    path('myoffers/', MyOffers.as_view(extra_context={'title': 'Мои заявки'}), name='myoffers'),
    path('myoffers/select/', set_selected_responder, name='select_responder'),
    path('myoffers/reset/', reset_selected_responder, name='reset_responder'),
    path('myrequests/', list_user_requests, name='list_requests'),
]

rar_net/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('offers.urls')),
    path('users/', include('users.urls')),
    path('locations/', include('locations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path

from .views import logout_user, login_user, RegisterUser

app_name = 'users'
urlpatterns = [
    path('logout/', logout_user, name='logout'),
    path('login/', login_user, name='login'),
    path('register/', RegisterUser.as_view(extra_context={'title': 'Регистрация'}), name='register'),
]

offers/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Offer(models.Model):
    categories = [
        ('buy', 'купить',),
        ('sell', 'продать',)
    ]

    statuses = [
        ('active', 'активно',),
        ('closed', 'закрыто',)
    ]

    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'
        ordering = ['id', 'title']

    title = models.CharField('название', max_length=150)
    description = models.CharField('описание', max_length=400, blank=True)
    category = models.CharField('категория', max_length=20, choices=categories, default='buy')
    status = models.CharField('статус', max_length=20, choices=statuses, default='active')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='author', verbose_name='владелец')
    responders = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='откликнулись', related_name='responders', blank=True)
    selected_responder = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='выбран', related_name='selected_responder', blank=True, null=True)
    pub_date = models.DateTimeField('дата публикации', auto_now_add=True)

    def __str__(self):
        return f'{self.title} | {self.author}'

class Photo(models.Model):
    class Meta:
        verbose_name = 'фото'
        verbose_name_plural = 'фотографии'

    offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    img = models.ImageField('фото', upload_to='offers/%Y/%m/')

    def __str__(self):
        return f'{self.img}'

offers/forms.py
from django import forms

from .models import Offer

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleImageField(forms.ImageField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class OfferForm(forms.ModelForm):
    imgs = MultipleImageField(label='Изображения')

    class Meta:
        model = Offer
        fields = ['title', 'description', 'category', 'imgs']

offers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotAllowed, HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Q

from .forms import OfferForm
from .models import Photo, Offer

# Create your views here.

def index(request):
    return render(request, 'offers/index.html', context={'offers': Offer.objects.filter(status='active')})

class CreateOffer(LoginRequiredMixin, generic.CreateView):
    template_name = 'offers/add_offer.html'
    redirect_field_name = ''
    form_class = OfferForm

    def get_success_url(self):
        return reverse_lazy('offers:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        self.object = form.save()

        images = form.cleaned_data['imgs']
        for img in images:
            Photo.objects.create(img=img, offer=self.object)

        return HttpResponseRedirect(self.get_success_url())

class DetailOffer(generic.DetailView):
    model = Offer
    template_name = 'offers/detail_offer.html'

    def get_context_data(self, *args, **kwargs):
        context = super(DetailOffer, self).get_context_data(*args, **kwargs)
        context['title'] = context['offer'].title
        return context

@login_required(redirect_field_name='')
def respond_to_offer(request, pk):
    if request.method == 'GET':
        offer = get_object_or_404(Offer, pk=pk)
        offer.responders.add(request.user)
        offer.save()

        return redirect('offers:index')
    else:
        return HttpResponseNotAllowed(['POST'])

class MyOffers(LoginRequiredMixin, generic.ListView):
    model = Offer
    template_name = 'offers/my_offers.html'
    redirect_field_name = ''

    def get_queryset(self):
        return self.request.user.author.all()

@login_required(redirect_field_name='')
def set_selected_responder(request):
    if request.method == 'POST':
        if request.POST is not None:
            offer_pk = request.POST['offer_pk']
            responder_pk = request.POST['responder_pk']

            offer = get_object_or_404(Offer, pk=offer_pk)
            responder = get_object_or_404(get_user_model(), pk=responder_pk)

            if offer.author == request.user:
                offer.selected_responder = responder
                offer.status = 'closed'
                offer.save()
            else:
                return HttpResponseForbidden()

            return redirect('offers:myoffers')
    else:
        return HttpResponseNotAllowed(['POST'])

@login_required(redirect_field_name='')
def reset_selected_responder(request):
    if request.method == 'POST':
        if request.POST is not None:
            offer_pk = request.POST['offer_pk']

            offer = get_object_or_404(Offer, pk=offer_pk)

            if offer.author == request.user:
                offer.selected_responder = None
                offer.status = 'active'
                offer.save()
            else:
                return HttpResponseForbidden()

            return redirect('offers:myoffers')
    else:
        return HttpResponseNotAllowed(['POST'])

@login_required(redirect_field_name='')
def list_user_requests(request):
    user_requests = request.user.responders.all()
    return render(request, 'offers/my_requests.html', context={'requests': user_requests})

def search(request):
    if request.GET is not None:
        query = request.GET['q']
        sort_type = request.GET['sort_type']

        initial_queryset = Offer.objects.filter(status='active')
        sorting_types = {
            'everywhere': lambda: initial_queryset,
            'same_country': lambda: initial_queryset.filter(author__country=request.user.country),
            'same_city': lambda: initial_queryset.filter(author__city=request.user.city),
        }

        sorted_offers = sorting_types.get(sort_type)()

        if query is not None:
            sorted_offers = sorted_offers.filter(Q(title__icontains=query) | Q(description__icontains=query))

        return render(request, 'offers/search_page.html', context={'offers': sorted_offers, 'q': query, 'sort_type': sort_type})

offers/templates/offers/components/offers_list.html
{% load static description %}
<section id="offers-list">
    <ul>
        {% for offer in offers %}
            <li>
                <div class="offer-card fancy-borders">
                    <a class="title" href="{% url "offers:detail_offer" offer.id %}">
                        <h3>{{offer.title}}</h3>
                    </a>
                    <p>{% description offer.description %}</p>
                    <div class="meta">
                        <span class="category {{offer.category|yesno:'buy,sell'}}">{{offer.get_category_display}}</span>
                        <div class="author-container">
                            <span class="author">{{offer.author.username}}</span>
                            {% if offer.author.country is not None %}
                                <img class="flag" title="{{offer.author.country.name}}" src="{% static "locations/flags/"|add:offer.author.country.flag %}" alt="">
                                <span class="city">{{offer.author.city.name}}</span>
                            {% endif %}
                        </div>
                    </div>
                    {% if user.is_authenticated and user.username != offer.author.username %}
                        {% if user in offer.responders.all %}
                            <a class="fancy-borders focus-button disabled">Вы уже откликнулись</a>
                        {% else %}
                            <a class="fancy-borders focus-button" href="{% url "offers:respond_offer" offer.id %}">Откликнуться</a>
                        {% endif %}
                    {% endif %}
                    <img src="{{offer.photo_set.first.img.url}}">
                </div>
            </li>
        {% endfor %}
    </ul>
</section>

offers/templates/offers/components/search.html
{% load static %}
<section class="fancy-borders search-bar flex{% if not user.is_authenticated %} center{% endif %}">
    {% if user.is_authenticated %}
    <div id="profile-container" class="flex">
        <a href="{% url "users:logout" %}">
            <img id="logout" src="{% static "offers/img/logout.png" %}" alt="выйти" title="выйти">
        </a>
        <span class="username">{{user.username}}</span>
        {% if user.country is not None %}
            <img class="flag" title="{{user.country.name}}" src="{% static "locations/flags/"|add:user.country.flag %}" alt="">
        {% endif %}
    </div>
    {% endif %}
    <div class="forms-container">
        {% if error %}
            <span class="error-message">{{error}}</span>
        {% endif %}
        {% if not user.is_authenticated %}
        <ul class="nav-links">
            <li><a id="login-button" href="#">Вход</a></li>
            <li><a href="{% url "users:register" %}">Регистрация</a></li>
        </ul>
        {% endif %}
        <form id="login-form" action="{% url "users:login" %}" method="post">
            {% csrf_token %}
            <input placeholder="имя" type="text" name="username" required>
            <input placeholder="пароль" type="password" name="password" required>
            <input type="submit" value="войти">
        </form>
        <form id="search-form" action="{% url "offers:search" %}" method="get">
            <input type="text" name="q" {% if q is not None %}value="{{q}}"{% endif %}>
            {% if user.is_authenticated %}
            <select name="sort_type">
                <option value="same_city" {% if sort_type == "same_city" %}selected{% endif %}>В моем городе</option>
                <option value="same_country" {% if sort_type == "same_country" %}selected{% endif %}>В моей стране</option>
                <option value="everywhere" {% if sort_type == "everywhere" or sort_type is None %}selected{% endif %}>Везде</option>
            </select>
            {% else %}
            <input type="hidden" name="sort_type" value="everywhere">
            {% endif %}
            <input type="submit" value="поиск">
        </form>
    </div>
    {% if user.is_authenticated %}
    <div>
        <ul class="actions">
            <li><a href="{% url "offers:list_requests" %}">Мои отклики</a></li>
            <li><a href="{% url "offers:myoffers" %}">Мои заявки</a></li>
            <li><a href="{% url "offers:add_offer" %}">Добавить заявку</a></li>
        </ul>
    </div>
    {% endif %}
</section>